ARG IMAGE_REPOSITORY=docker.io/library  \
    IMAGE_DEBIAN_VERSION=bookworm-slim

FROM --platform=$TARGETPLATFORM $IMAGE_REPOSITORY/debian/$IMAGE_DEBIAN_VERSION AS qor-caddy
WORKDIR /app

ARG IMAGE_MIRROR_REPO

ENV DEBIAN_FRONTEND=noninteractive

COPY --from=$IMAGE_MIRROR_REPO --chmod=0755 /app/bin/caddy /app/caddy
COPY --chmod=0755 scripts/docker-entrypoint.sh /app/scripts/docker-entrypoint.sh

RUN apt-get update; apt-get upgrade -y; apt install -y \
        ca-certificates \
        openssl \
    && useradd \
        --home-dir "/app"     \
        --shell "$CONT_SHELL" \
        --uid "$CONT_UID"     \
        --disabled-password   \
        --no-create-home      \
        "$CONT_USER" \
    && mkdir -p /var/www/ \
    && chown -R "$CONT_UID" /var/www /app \
    && rm -rf /var/cache/apt

USER "$CONT_UID"

ENTRYPOINT /app/scripts/docker-entrypoint.sh
