ARG IMAGE_REPOSITORY \
    IMAGE_ALPINE_VERSION

FROM $IMAGE_REPOSITORY/alpine:$IMAGE_ALPINE_VERSION AS qor-caddy
WORKDIR /app

ARG ALPINE_REPO_URL=https://dl-cdn.alpinelinux.org/alpine \
    ALPINE_REPO_VERSION=v3.19 \
    CONT_USER=caddy \
    CONT_UID=1001

LABEL stage=qor-caddy

COPY --from=ghcr.io/rubberverse/xcaddy-helper --chmod=0755 /app/bin/caddy /app/caddy
COPY --chmod=755 scripts/docker-entrypoint.sh /app/scripts/docker-entrypoint.sh

RUN apk upgrade --no-cache; apk add --no-cache --repository=${ALPINE_REPO_URL}/${ALPINE_REPO_VERSION}/main \
        ca-certificates \
        openssl         \
    && adduser \
        --home "/app"          \
        --shell "/bin/ash"     \
        --uid "$CONT_UID"      \
        --disabled-password    \
        --no-create-home       \
        "$CONT_USER" \
    && mkdir -p /app/logs \
    && chown -R "$CONT_UID" /srv /app

USER ${CONT_UID}

ENTRYPOINT /app/scripts/docker-entrypoint.sh
