ARG IMAGE_GHCR_REPOSITORY=ghcr.io/rubberverse
ARG QOR_HELPER_TYPE=qor-helper-dev:donotuse-latest
ARG TARGETPLATFORM

FROM --platform=$TARGETPLATFORM ${IMAGE_GHCR_REPOSITORY}/${QOR_HELPER_TYPE} AS qor-helper-dev
# le edging the FROM prompt moment

FROM --platform=$TARGETPLATFORM docker.io/library/debian:bookworm-slim AS qor-caddy
WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

COPY --from=ghcr.io/rubberverse/xcaddy-helper --chmod=0755 /app/bin/caddy /app/caddy
COPY --chmod=0755 scripts/docker-entrypoint.sh /app/scripts/docker-entrypoint.sh

RUN apt-get update; apt-get upgrade -y; apt install -y \
        ca-certificates \
        openssl \
        libcap-ng0 \
        libcap-ng-utils \
    && useradd \
        --home-dir "/app"     \
        --shell "$CONT_SHELL" \
        --uid "$CONT_UID"     \
        --disabled-password   \
        --no-create-home      \
        "$CONT_USER" \
    && mkdir -p /var/www/ \
    && chown -R "$CONT_UID" /var/www /app \
    && setcap 'cap_net_bind_service+ep' /app/caddy \
    && apt remove libcap-ng0 libcap-ng-utils -y \
    && rm -rf /var/cache/apt

USER "${CONT_UID}"

ENTRYPOINT /app/scripts/docker-entrypoint.sh
