ARG IMAGE_GHCR_REPOSITORY=ghcr.io/rubberverse
ARG QOR_HELPER_TYPE=qor-helper-dev:donotuse-latest

FROM --platform=$TARGETPLATFORM ghcr.io/rubberverse/qor-helper-dev:donotuse-latest AS qor-helper-dev

FROM docker.io/library/alpine:3.19.1 AS qor-caddy
WORKDIR /app

ARG ALPINE_REPO_URL=https://dl-cdn.alpinelinux.org/alpine
ARG ALPINE_REPO_VERSION=v3.19
ARG CONT_USER=caddy
ARG CONT_UID=1001

LABEL stage=qor-caddy

COPY --from=qor-helper-dev --chmod=0755 /app/bin/caddy /app/bin/caddy
COPY --chmod=755 ../scripts/docker-entrypoint.sh /app/scripts/docker-entrypoint.sh

RUN apk upgrade \
    && apk add --no-cache --repository=${ALPINE_REPO_URL}/${ALPINE_REPO_VERSION}/main \
        ca-certificates \
        openssl \
    && adduser \
        --home "/app" \
        --shell "/bin/ash" \
        --uid "$CONT_UID"  \
        --disabled-password \
        --no-create-home \
        "$CONT_USER" \
    && mkdir -p /app/logs /srv/www \
    && chown -R "$CONT_UID" /srv /app

USER $CONT_UID

ENTRYPOINT /app/scripts/docker-entrypoint.sh