FROM --platform=$TARGETPLATFORM ghcr.io/rubberverse/cc-caddy-binary:latest AS qor-helper-dev

FROM docker.io/library/alpine:edge AS qor-caddy
WORKDIR /app

ARG ALPINE_REPO_URL=https://dl-cdn.alpinelinux.org/alpine \
    ALPINE_REPO_VERSION=v3.19 \
    CONT_USER=caddy \
    CONT_SHELL="/bin/sh" \
    CONT_UID=1001

ARG TARGETARCH

LABEL stage=qor-caddy

COPY --from=qor-helper-dev --chmod=0755 /app/go/bin/caddy-${TARGETARCH} /app/bin/caddy
COPY --chmod=755 ../scripts/docker-entrypoint.sh /app/scripts/docker-entrypoint.sh

RUN apk update \
    && apk upgrade --no-cache \
    && apk add --no-cache --repository=${ALPINE_REPO_URL}/${ALPINE_REPO_VERSION}/main \
        ca-certificates \
        openssl \
    && adduser \
        --home "/app" \
        --shell "$CONT_SHELL" \
        --uid "$CONT_UID"  \
        --disabled-password \
        --no-create-home \
        "$CONT_USER" \
    && mkdir -p /app/logs /srv/www \
    && chown -R "$CONT_UID":"$CONT_UID" /app /srv/www

USER $CONT_UID

ENTRYPOINT /app/scripts/docker-entrypoint.sh
