FROM --platform=$TARGETPLATFORM ghcr.io/rubberverse/cc-caddy-binary:latest AS qor-helper-dev

FROM --platform=$TARGETPLATFORM docker.io/library/debian:bookworm-slim AS qor-caddy
WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ARG CONT_USER=caddy \
    CONT_SHELL=/bin/sh \
    CONT_UID=1001

ARG TARGETARCH

COPY --from=qor-helper-dev --chmod=0755 /app/go/bin/caddy-${TARGETARCH} /app/bin/caddy
COPY --chmod=0755 ../scripts/docker-entrypoint.sh /app/scripts/docker-entrypoint.sh

RUN apt-get update; apt-get upgrade -y; apt install -y \
        ca-certificates \
        openssl \
    && useradd \
        --home-dir "/app" \
        --shell "$CONT_SHELL" \
        --uid "$CONT_UID" \
        --no-create-home \
        "$CONT_USER" \
    && mkdir -p /var/www/ \
    && chown -R "$CONT_UID":"$CONT_UID" /var/www /app \
    && rm -rf /var/cache/apt

USER "${CONT_UID}"

ENTRYPOINT /app/scripts/docker-entrypoint.sh