# v1.0.3
ARG IMAGE_REPOSITORY=docker.io/library
ARG IMAGE_ALPINE_VERSION=edge

ARG BUILDPLATFORM

FROM --platform=$BUILDPLATFORM $IMAGE_REPOSITORY/alpine:$IMAGE_ALPINE_VERSION AS alpine-builder
WORKDIR /app

ARG TARGETOS
ARG TARGETARCH
ARG CADDY_MODULES

LABEL stage=alpine-builder

ARG ALPINE_REPO_URL=https://dl-cdn.alpinelinux.org/alpine \
    REMOTE_URL=https://raw.githubusercontent.com/caddyserver/caddy/master/cmd/caddy/main.go \
    CADDY_BRANCH_VERSION=v2.8.0-beta.2 \
    ALPINE_REPO_VERSION=v3.19 \
    GOCACHE=/app/go/cache \
    GOOS $TARGETOS \
    GOARCH $TARGETARCH \
    GIT_WORKTREE=/app/worktree \
    CGO_ENABLED=0 \
    GO_BUILD_FLAGS="-trimpath" \
    CADDY_MODULES=""

COPY --chmod=0755 ../scripts/array-helper.sh \ 
    /app/helper/array-helper.sh

# build deps: jq, git, tar, bash, curl
RUN apk upgrade --no-cache \
    && apk add --no-cache --virtual build_ess --repository=${ALPINE_REPO_URL}/${ALPINE_REPO_VERSION}/main \
        jq \
        git \
        tar \
        bash \
        curl \
        file \
        ca-certificates \
    && export GO_VERSION=$(curl https://go.dev/dl/?mode=json | jq -r '.[0].version' ) \
    && curl -LO go.dev/dl/${GO_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf "${GO_VERSION}".linux-amd64.tar.gz \
    && rm "${GO_VERSION}".linux-amd64.tar.gz \
    && export PATH=${PATH}:/usr/local/go/bin:/app/go/bin \
    && git config --global --add safe.directory '*' \
    && mkdir -p caddy \
    && curl -L "${REMOTE_URL}" -o caddy/main.go \
    && cd caddy \
    && go mod init caddy \
    && /app/helper/array-helper.sh \
    && GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" go build -v ${GO_BUILD_FLAGS} -ldflags '-s -w' -o /app/go/bin/caddy-"${TARGETARCH}" -gcflags=all="-N -l" ./ \
    && ls -l /app/go/bin \
    && file /app/go/bin/caddy-"${TARGETARCH}" \
    && apk del --rdepends \
        build_ess \
    && rm -rf /app/go/cache /app/git /tmp /app/caddy /usr/local/go /app/worktree