name: Build Alpine & Debian image and push to GHCR

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - '.github/workflows/**.yaml'
  workflow_dispatch:

jobs:
  build:
    name: Build and push to ghcr
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write
      contents: write
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Free up worker space
        run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"; sudo rm -rf /usr/share/dotnet /usr/local/lib/android; sudo apt-get update; sudo apt-get remove -y '^dotnet-.*'; sudo apt-get autoremove -y; sudo apt-get clean
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Alpine Image to GHCR
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: qor-caddy
          registry: ghcr.io
          dockerfile: caddy-dfs-CC/alpine/Dockerfile
          buildArgs: BUILDPLATFORM=linux/amd64,CADDY_MODULES="github.com/greenpau/caddy-security github.com/mholt/caddy-ratelimit github.com/fvbommel/caddy-dns-ip-range github.com/WeidiDeng/caddy-cloudflare-ip github.com/fvbommel/caddy-combine-ip-ranges github.com/caddy-dns/porkbun github.com/caddy-dns/cloudflare github.com/caddy-dns/vercel github.com/mholt/caddy-dynamicdns github.com/corazawaf/coraza-caddy/v2 github.com/hslatman/caddy-crowdsec-bouncer/http github.com/hslatman/caddy-crowdsec-bouncer/layer4 github.com/jonaharagon/caddy-umami",GO_CADDY_VERSION=v2.9.0
          platform: linux/amd64
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build & Push Debian Image to GHCR
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: qor-caddy
          registry: ghcr.io
          dockerfile: caddy-dfs-CC/debian/Dockerfile
          buildArgs: BUILDPLATFORM=linux/amd64,CADDY_MODULES="github.com/greenpau/caddy-security github.com/mholt/caddy-ratelimit github.com/fvbommel/caddy-dns-ip-range github.com/WeidiDeng/caddy-cloudflare-ip github.com/fvbommel/caddy-combine-ip-ranges github.com/caddy-dns/porkbun github.com/caddy-dns/cloudflare github.com/caddy-dns/vercel github.com/mholt/caddy-dynamicdns github.com/corazawaf/coraza-caddy/v2 github.com/hslatman/caddy-crowdsec-bouncer/http github.com/hslatman/caddy-crowdsec-bouncer/layer4 github.com/jonaharagon/caddy-umami",GO_CADDY_VERSION=v2.9.0
          platform: linux/amd64
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Cancel on failure
        uses: andymckay/cancel-action@0.4
