name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  ALPINE_VERSION: ${{vars.ALPINE_VERSION}}
  CADDY_VERSION: ${{vars.CADDY_VERSION}}
  BUILD_VERSION: ${{vars.BUILD_VERSION}}

jobs:
  build:
    name: Build, Push and Deploy the Image
    runs-on: ubuntu-latest
      
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to ghcr.io
        with:
          image: qor-caddy
          tags: ${{env.BUILD_VERSION}}-${{env.CADDY_VERSION}}, caddy-${{env.CADDY_VERSION}}-alpine-${{env.ALPINE_VERSION}}-build-${{env.BUILD_VERSION}}
          buildArgs: ALPINE_VERSION=${{env.ALPINE_VERSION}} CADDY_VERSION=${{env.CADDY_VERSION}} BUILD_VERSION=${{env.BUILD_VERSION}}
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
