name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Set Environmental Variables'
            run: |
              echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
              echo "CADDY_VERSION=${CADDY_VERSION}" >> $GITHUB_ENV
              echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV 

          - name: 'Build the image'
            run: |
              docker build . --tag ghcr.io/Rubberverse/qor-caddy:${{env.BUILD_VERSION}}
              docker push ghcr.io/Rubberverse/qor-caddy:${{env.BUILD_VERSION}} --build-args alpine_version=${{env.ALPINE_VERSION}} --build-args caddy_version=${{env.CADDY_VERSION}} --build-args build_version=${{env.BUILD_VERSION}}
