name: Deploy Images to GHCR and Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - '.github/workflows/publish.yaml'
  workflow_dispatch:

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: .
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

     # - name: Minor version for each merge
     #   id: autotagger
     #   uses: anothrNick/github-tag-action@1.67.0
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #     WITH_V: true

      - uses: docker/setup-buildx-action@v3
        name: Customize Docker driver
        with:
          driver-opts: image=moby/buildkit:master
          
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Alpine variant of the image
        with:
          image: qor-helper
          tags: DONOTUSE-${RANDOM}${RANDOM}, DONOTUSE-latest
          buildArgs: BUILDPLATFORM=linux/amd64
          dockerfile: Dockerfile-Helper
          registry: ghcr.io
          multiPlatform: true
          overrideDriver: true
          enableBuildKit: true
          platform: linux/amd64,linux/i386,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/mips64le,linux/s390x
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Alpine variant of the image
        with:
          image: qor-caddy-dev
          tags: DONOTUSE-${RANDOM}${RANDOM}-ALPINE, DONOTUSE-ALPINE-latest
          buildArgs: BUILDPLATFORM=linux/amd64
          dockerfile: Dockerfile-Alpine
          registry: ghcr.io
          multiPlatform: true
          overrideDriver: true
          enableBuildKit: true
          platform: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Alpine variant of the image
        with:
          image: qor-caddy-dev
          tags: DONOTUSE-${RANDOM}${RANDOM}-DEBIAN, DONOTUSE-DEBIAN-latest
          buildArgs: BUILDPLATFORM=linux/amd64
          dockerfile: Dockerfile-Debian
          registry: ghcr.io
          multiPlatform: true
          overrideDriver: true
          enableBuildKit: true
          platform: linux/amd64,linux/i386,linux/arm/v5,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- uses: mr-smithers-excellent/docker-build-push@v6
      #  name: Build & push Docker image to docker.io for ${{ matrix.db-type }}
      #  with:
      #    image: mrrubberducky/qor-caddy
      #    tags: ${{ steps.autotagger.outputs.new_tag }}, latest
      #    buildArgs: BUILDPLATFORM=linux/amd64
      #    registry: docker.io
      #    multiPlatform: true
      #    overrideDriver: true
      #    enableBuildKit: true
      #    platform: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
