name: Deploy Images to GHCR and Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - '.github/workflows/publish.yaml'
  workflow_dispatch:

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: .
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Minor version for each merge
        id: autotagger
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: docker/setup-buildx-action@v3
        name: Customize Docker driver
        with:
          driver-opts: image=moby/buildkit:master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Multi-Arch Docker Image
        with:
          image: qor-caddy
          tags: ${{ steps.autotagger.outputs.new_tag }}, latest
          registry: ghcr.io
          multiPlatform: true
          overrideDriver: true
          platform: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to docker.io for ${{ matrix.db-type }}
        with:
          image: mrrubberducky/qor-caddy
          tags: ${{ steps.autotagger.outputs.new_tag }}, latest
          registry: docker.io
          multiPlatform: true
          overrideDriver: true
          platform: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
