name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build, Push and Deploy the Image
    runs-on: ubuntu-latest
    environment: production
    env:
      ALPINE_LINUX: ${{ vars.ALPINE_LINUX }}
      CADDY_VERSION: ${{ vars.CADDY_VERSION }}
      BUILD_VERSION: ${{ vars.BUILD_VERSION }}

    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@main
    
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/main}" >> $GITHUB_ENV

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to ghcr.io
        with:
          image: rubberverse/qor-caddy
          registry: ghcr.io
          enableBuildKit: true
          githubOrg: rubberverse
          tags: build-${{ env.RELEASE_VERSION }}, latest-${{ env.BUILD_VERSION }}
          dockerfile: Caddy.Dockerfile
          buildArgs: ALPINE_VERSION=${{ env.ALPINE_VERSION }}, CADDY_VERSION=${{ env.CADDY_VERSION }}, BUILD_VERSION=${{ env.BUILD_VERSION }}
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
