name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build the image'
            run: |
              docker build . --tag ghcr.io/Rubberverse/qor-caddy:${{ vars.BUILD_VERSION }}
              docker push ghcr.io/Rubberverse/qor-caddy:${{ vars. BUILD_VERSION }} --build-args alpine_version=${{ vars.ALPINE_VERSION }} --build-args caddy_version=${{ vars.CADDY_VERSION}} --build-args build_version=${{ vars.BUILD_VERSION }}
